spring.datasource.url=jdbc:tc:mysql:8.4.4:///tennisgame
spring.datasource.username=test
spring.datasource.password=test

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration